### ISSUE TITLE
GetField Raw Output

### ISSUE THREAD

**Issue by RobertKlohr** [MircoBabin/KeePassCommander#10]
Is there a way to get just the raw output e.g., the value in the field, for the GetField command?

Currently the command KeePassCommand.exe getfield "KeePass-entry-title" "Password" returns the following text that must be parsed before it can be used. I'm assuming the B = Begin and E = End, and I = Item or Iteration.

SUCCESS
B
I       title   KeePass-entry-title
I       Password        notTheRealPassword
E

The challenge I am having is consistently being able to parse out the content depending on which application is calling KeePassCommand. Ideally there would be a new command, following your current naming standard, like "getfieldraw" that when used would return just the field contents and none of the meta data and would look like the following example.

KeePassCommand.exe getfieldraw "KeePass-entry-title" "Password"
notTheRealPassword

**Comment by MircoBabin** [comment]
In what programming language (php, powershell, c#, python, bat-file, ...) do you want to retrieve the password (and/or other values) ?

There are already a number of Programming Language Connectors, parsing the raw output into fields. See https://github.com/MircoBabin/KeePassCommander/tree/master/src/ProgrammingLanguagesConnectors

Also see https://github.com/MircoBabin/KeePassCommander/tree/master/example for examples of how to use the Programming Language Connectors.

**Comment by MircoBabin** [comment]
Version 3.0 implements a new getfieldraw command.

**Comment by johnd0e** [comment]
> Version 3.0 implements a new getfieldraw command.

For security purposes it would be nice to just output the value instead of saving it to file.

**Comment by MircoBabin** [comment]
I just published a new version. Which allows output to the console (stdout).

**Comment by johnd0e** [comment]
Thank you!
Perhaps the help text should be updated as well?

**Comment by MircoBabin** [comment]
Regarding the helptext, it is updated. The version should show 4.4. Or do you see something else?

```
KeePassCommand 4.4
https://github.com/MircoBabin/KeePassCommander - MIT license
```


```
* Advanced get string field RAW
…
- Without -out*, "Value" is outputted at the console (STDOUT).
```

Same for 
`* Advanced get file attachment RAW ` and 
`* Advanced get note RAW `.

**Comment by johnd0e** [comment]
You are right. I have missed it, because I was looking for `-stdout-utf8`(`nobom`) in related sections only.

It's not so easy to figure out that such options ever exist, without thoroughly reading the entire help text from the very beginning.
