### ISSUE TITLE
Lua programming language connector

### ISSUE THREAD

**Issue by johnd0e** [MircoBabin/KeePassCommander#11]
I am interested in using the same functionality directly, without `KeePassCommand.exe`.
Is it possible to achieve this with the plain Windows API?

**Comment by MircoBabin** [comment]
The communication uses `Windows Named Pipes` or `files on the filesystem`. Which are part of the plain Windows API. But the communication is not documented. So I do not advice to program your own `KeePassCommand.exe`.

In what programming language do you want to implement this? Or what is your use case?

There is C# code for communication: 
- See https://github.com/MircoBabin/KeePassCommander/tree/master/src/KeePassCommandDll/Communication for the communication stuff.
- See https://github.com/MircoBabin/KeePassCommander/blob/master/src/Encryption.cs for the encryption stuff.

**Comment by johnd0e** [comment]
Thank you!
It works, but `attachments` and `fields` are always empty.

**Comment by MircoBabin** [comment]
You should also specify the name of the attachment.

e.g.
`KeePassCommand.exe getattachment "test!" ”private-key.pem”`

In this case in KeePass the entry “title!” Should have an attachment named “private-key.pem”.

KeePassCommander by default does only return things you know. As a security measure. You can’t use KeePassCommander to just list everything what is available in all open KeePass databases.

**Comment by MircoBabin** [comment]
`Options.AttachmentNames` should be filled with the attachment names you want returned for the “test!” Entry.

Same goes for `Options.FieldNames`.

**Comment by johnd0e** [comment]
Thank you, now it is clear.
