### ISSUE TITLE
`listgroup` not working

### ISSUE THREAD

**Issue by johnd0e** [MircoBabin/KeePassCommander#12]
`KeePassCommand.exe listgroup "All Entries"` or `KeePassCommand.exe listgroup "General"` outputs nothing.

Also, the following help text is not clear to me:

> - The queried entry note may contain the line "KeePassCommanderListGroup=true".
>   This is not recursive, only titles in the current group are listed.
> - The queried entry note may contain lines "KeePassCommanderListAddItem={title}".

What is the purpose of mentioned notes?

**Comment by MircoBabin** [comment]
KeePassCommander by default does only return things you know. As a security measure. You can’t use KeePassCommander to just list everything what is available in all open KeePass databases.

For `ListGroup` it means in the notes section of the entry you specify like “General” must exist. And in the notes section of this “General” entry explicitly must be specified which titlenames will be returned. See https://github.com/MircoBabin/KeePassCommander/blob/master/docs/ListGroup.md

“General” is not the name of a group, but of an entry.

**Comment by johnd0e** [comment]
> “General” is not the name of a group, but of an entry.

Now i see it, thank you.

So "General" should be just a stub item, that triggers listing of the group, in which it is itself placed.
Wow, that is extreme unobvious.
Perhaps help text should be improved.

**Comment by MircoBabin** [comment]
I opened issue #15 for the helptext.
