### ISSUE TITLE
`getfieldraw` does not work when there more than 1 entry with given name exists

### ISSUE THREAD

**Issue by johnd0e** [MircoBabin/KeePassCommander#13]

**Comment by johnd0e** [comment]
`getfield` has no this problem, but.. still not helpful.

Perhaps the main issue is that there is no possibility to differentiate between same-named entries.
Is it possible to specify additional data, like group name?

**Comment by MircoBabin** [comment]
The simplest solution is to rename the titles in KeePass. So that they are unique.

E.g. when having 2 entries "test!" rename one to "test! staging" and one to "test! local" or something like that.

**Comment by MircoBabin** [comment]
* It is not a workaround. It is awkward having duplicate titles in KeePass. Because then you can never explicitly target the correct one with KeePassCommander.

* Also `getfieldraw` can only output 1 entry. It would not make sense to output multiple entries.

* I see it the other way around. `get`,  `getfield`,  `getattachment` should return nothing if duplicate titles are queried.

**Comment by johnd0e** [comment]
> Because then you can never explicitly target the correct one with KeePassCommander.

Well, it is also common to delete duplicate entries. Then they get into the Recycle Bin.
I believe that Recycle Bin items should be skipped anyway - KeePass itself ignores it during search.

And you have not replied on my idea "Is it possible to specify additional data, like group name?"

> Also getfieldraw can only output 1 entry. It would not make sense to output multiple entries.

Consider also a case when you have 2 items, but only 1 has required field. So it makes sense at least to try to process several items.

> I see it the other way around. get, getfield, getattachment should return nothing if duplicate titles are queried.

Even if so, what about to output clear error message? There is stderr for this. And exit code.
It would be very helpful, for all commands, not only "getfieldraw"

For example right now I have an issue, trying to process one of the entries: it just not work, outputs nothing.
There are no duplicates, and I tried to rename the entry - without success.

**Comment by MircoBabin** [comment]
> I believe that Recycle Bin items should be skipped anyway - KeePass itself ignores it during search.

I find this a good suggestion. The next time I’m doing something in KeePassCommander I will try to implement this. It may however take weeks/months before I have time to do so. I opened #16 for this.

> And you have not replied on my idea "Is it possible to specify additional data, like group name?"

No this is not possible. The title must be unique and explicitly case sensitive specified. There is no fuzzy search as a security measure.

> Even if so, what about to output clear error message?

I agree that error messages can be improved I opened #17 for this.

**Comment by johnd0e** [comment]
> There is no fuzzy search as a security measure.

But if would be possible to specify a group - it would be even more secure, don't you think?
In both meanings:
- I must know not only the exact name, but the exact group as well
- It is harder to make a mistake requesting wrong item - with similar name but completely different group

**Comment by MircoBabin** [comment]
> But if would be possible to specify a group - it would be even more secure, don't you think?

No, also having to specify the group brings no benefit.

* The title must be unique. Also supplying the group is superfluous.
* Moving the entry to another group then breaks querying the title.
* It does not bring more security. Only more annoyance. This would then go into a kind of pairing which just complicates things.

> It is harder to make a mistake requesting wrong item - with similar name but completely different group

it is easier to make a mistake. Now you would have to type both the title and the group correctly. Which doubles the chance of mistakes versus only having to type the title correctly.

**Comment by johnd0e** [comment]
> The title must be unique.

Define "must".
KeePass does not limit me to create duplicate titles, they can appear even without explicit intention.

> It does not bring more security. Only more annoyance. This would then go into a kind of pairing which just complicates things.

Depends on use case.
I am trying to get not arbitrary item, but that I previously listed with "list" command.

So as I see it - as I've got item info with "group" argument - it would be pretty consistent to use same "group" argument in get command.

**Comment by MircoBabin** [comment]
> Define "must".

For KeePassCommander to work correctly, the title in KeePass must be unique.

**Comment by MircoBabin** [comment]
I’m not going to add `group` into KeePassCommander.
