### ISSUE TITLE
Using the same zip filename for each new releases in github

### ISSUE THREAD

**Issue by fstemarie** [MircoBabin/KeePassCommander#7]
Hi !
I am writing a powershell script using boxstarter and Chocolatey that will configure my entire system after a reinstall.
In this script, I install KeePass and a series of plugins including KeePassCommander. The problem is that it is difficult to automatically download the zip file of the latest release since the release number is in the file name and therefore, changes with every release.
Github has made it possible to download the latest release of a project using a URL like this
https://github.com/MircoBabin/KeePassCommander/releases/latest/download/KeePassCommander.zip
Putting the release number in the filename defeats that purpose and prevents from using automation.
Enabling automation also means the potential for making a nuget or scoop package.

So my suggestion would be to simply name the releases KeePassCommander.zip instead of Release_2.5.zip

Thank you !

**Comment by MircoBabin** [comment]
I am assuming you want to automatically install a predefined set of versions. E.g. KeePass 2.50 + KeePassCommander 2.5.

When KeePass releases for example version 3.0 I assume you do not want that automatically installed, because it's not tested with KeePassCommander 2.5. Or the other way around: KeePassCommander releases version 3.0 which is only compatible with an upcoming (not yet released) KeePass version. So automatically installing the latest KeePassCommander version is not a great idea, because it depends on the KeePass version. And could result in a non working installation.

My advice would be to install a fixed KeePass version and a fixed KeePassCommander version using https://github.com/MircoBabin/KeePassCommander/releases/download/2.5/Release_2.5.zip

Is this a viable solution ?

**Comment by fstemarie** [comment]
All I intended to do was make a boxstarter script that installs the latest version of KeePass with the latest version of KeePassCommander and deal with versions mismatch manually if needed. The fact that the zip filename may change between versions mean that the latest version cannot be downloaded automatically. If I really wanted to download a specific version, I could easily find a link to it like you did. I do not need to keep a specific version of KeePass, I keep it up to date. I imagine that you maintain KeePassCommander so it works with the latest version. So in my script, I get the latest version of KeePass and I would like to always be able to get the latest version of KeePassCommander without having to keep my script up to date. This can be achieved if the link to the latest version of KeePassCommander is static.
With https://github.com/MircoBabin/KeePassCommander/releases/latest/download/KeePassCommander.zip, I never have to change my script.
With https://github.com/MircoBabin/KeePassCommander/releases/download/2.5/Release_2.5.zip, I have to change my script with every new version

I imagine that others could benefit from it too, but hey, it's your project and I will respect your decision.

**Comment by MircoBabin** [comment]
I want to keep the releasenumber in the filename. It's a personal preference.

To facilitate your request, is the following flow usable for you?
1) A new file is published: https://github.com/MircoBabin/KeePassCommander/releases/latest/download/release.latest.download.url 
2) This file contains a url like

**Comment by MircoBabin** [comment]
I want to keep the releasenumber in the filename. It's a personal preference.

To facilitate your request, is the following flow usable for you?

1) KeePassCommander publishes a new file: https://github.com/MircoBabin/KeePassCommander/releases/latest/download/release.download.zip.url
This file is a text file and only contains an url like  https://github.com/MircoBabin/KeePassCommander/releases/download/2.5/Release_2.5.zip

2) Your script would have to:
2.1) download https://github.com/MircoBabin/KeePassCommander/releases/latest/download/release.download.zip.url
2.2) read the contents from the file into download-url
2.3) download the real installation zip from the download-url

**Comment by MircoBabin** [comment]
I have just published https://github.com/MircoBabin/KeePassCommander/releases/latest/download/release.download.zip.url. So you can try it out.

**Comment by fstemarie** [comment]
Yes thank you !
