### ISSUE TITLE
Add a version information file to support keepass' update check function

### ISSUE THREAD

**Issue by rasa** [MircoBabin/KeePassCommander#8]
Details [here](https://keepass.info/help/v2_dev/plg_index.html#upd).

**Comment by MircoBabin** [comment]
I'm going to investigate this. It may take several weeks before I have time to do so.

**Comment by MircoBabin** [comment]
I have released version 2.7. This version implements the KeePass check for updates mechanism.

(But only at the release of version 2.8 one will know if it works.)
